### ISSUE TITLE
This event loop is already running

### ISSUE THREAD

**Issue by mineshgandhi78** [bisohns/search-engine-parser#154]
![image](https://user-images.githubusercontent.com/92354904/146749239-233f9521-f1fb-43b0-be1c-536592c884c8.png)

**Comment by AindriyaBarua** [comment]
I am facing the same issue

**Comment by sj7272** [comment]
Same for me

**Comment by btreecat** [comment]
What if you try to do `gsearch.async_search()`

**Comment by CaoHaiNam** [comment]
> What if you try to do `gsearch.async_search()`

I tried, but it does not work. Do you have any ideas to fix it?

**Comment by deven96** [comment]
Similar to #147 ?
