### ISSUE TITLE
Upgrade version

### ISSUE THREAD

**Issue by iamgojoof6eyes** [bisohns/search-engine-parser#161]
Upgrade your dependency to at least the latest version of dependencies you have used. Because dependbot throwing errors with the version lower than 4.6.5 of lxml. And if you want to say we have already done it, then that's not taking effect.....you can try it by ourself or just take a look here
![Screenshot_16](https://user-images.githubusercontent.com/91426868/169231544-e0dbf95f-dd6d-4650-860b-e1544a8a0547.jpg)

**Comment by MeNsaaH** [comment]
Fixed in #181
