### ISSUE TITLE
Update dependecy versions

### ISSUE THREAD

**Issue by iamgojoof6eyes** [bisohns/search-engine-parser#175]
I respect your hard work and time spent building this amazing module for python.....but it is my humble request that please upgrade the lxml version to the latest version because the current lxml version you are using giving an alert to upgrade in my repo....if I upgrade it then deploy it....it says following
 The conflict is caused by:
           The user requested lxml==4.9.1
           search-engine-parser 0.6.7 depends on lxml==4.6.5

**Comment by deven96** [comment]
Could you bump up the version and open a PR?

**Comment by iamgojoof6eyes** [comment]
thx for updating :heart:

**Comment by iamgojoof6eyes** [comment]
Maybe the dependabot has already done it right?

**Comment by iamgojoof6eyes** [comment]
Actually, I have just seen that merge.

**Comment by deven96** [comment]
Yes it has thanks

**Comment by iamgojoof6eyes** [comment]
Even after upgrading it is still creating conflict while deploying the app
[![Pic](https://te.legra.ph/file/d42f7d384d6d8193e4d01.jpg)]
