### ISSUE TITLE
"Blessed needs Python 3.2.3 or greater" error on Python 3.10.5

### ISSUE THREAD

**Issue by roelvangils** [bisohns/search-engine-parser#176]
**Describe the bug**

When I run the command with the same parameters as in the documentation (`pysearch --engine bing  --type descriptions "Preaching to the choir"`), I receive this error:

```
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/bin/pysearch", line 5, in <module>
    from search_engine_parser.core.cli import runner
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/search_engine_parser/core/cli.py", line 11, in <module>
    from blessed import Terminal
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/site-packages/blessed/__init__.py", line 15, in <module>
    raise ImportError('Blessed needs Python 3.2.3 or greater for Python 3 '
ImportError: Blessed needs Python 3.2.3 or greater for Python 3 support due to http://bugs.python.org/issue10570.
```

**To Reproduce**
I followed all the installation instructions. I'm on macOS 12.5 and my Python version is 3.10.5.

**Desktop (please complete the following information):**
 - OS: macOS 12.5
 - Python Version 3.10.5
 - Search-engine-parser version: latest

**Additional context**
The error says `Blessed needs Python 3.2.3 or greater for Python 3`, but I have Python 3.10.5. Could it be possible that the parsing of the version number is wrong, so it thinks my version is older (3.1...)?

**Comment by roelvangils** [comment]
I managed to fix this by uninstalling and reinstalling the `blessed` dependency. Now I'm on version 1.19.1 instead of 1.15.

```
pip3 uninstall blessed
pip3 install blessed
```

(Maybe this is helpful to other newbies like myself.)

**Comment by deven96** [comment]
Thanks @roelvangils
