### ISSUE TITLE
Install error on python 3.11

### ISSUE THREAD

**Issue by malinkinsa** [bisohns/search-engine-parser#179]
**Describe the bug**
Installation failed on python3.11. 
Separately i can install lxml in this python version, but if it is installed in env - error is reprodused

**To Reproduce**
1. Try to install via pip on python 3.11 
2. See error:

```
pip3.11 install search-engine-parser
Defaulting to user installation because normal site-packages is not writeable
Collecting search-engine-parser
  Using cached search_engine_parser-0.6.7-py3-none-any.whl (37 kB)
Collecting lxml==4.6.5
  Using cached lxml-4.6.5.tar.gz (3.2 MB)
  Preparing metadata (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.
  │ exit code: 1
  ╰─> [3 lines of output]
      Building lxml version 4.6.5.
      Building without Cython.
      Error: Please make sure the libxml2 and libxslt development packages are installed.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: metadata-generation-failed

× Encountered error while generating package metadata.
╰─> See above for output.

note: This is an issue with the package mentioned above, not pip.
hint: See above for details.
```

**Desktop (please complete the following information):**
 - OS: Debian 11 bullseye
 - Python Version: 3.11
 - Search-engine-parser version: 0.6.7

**Additional context**
I made a fork and successfully installed it via pip after removing the version lock in requirements.txt

**Comment by deven96** [comment]
So the latest lxml fixes this?

**Comment by MeNsaaH** [comment]
This looks like a dependency error. Ensure you have libxml2-dev and libxslt-dev installed on your system. YOu can installed those using
```bash
apt install libxml2-dev libxslt-dev
```

**Comment by malinkinsa** [comment]
@deven96 no, same error. Fresh Install inside venv only lxml work fine, but after when i try to install your packets - error from first topic.

@MeNsaaH ok, i try it tomorrow

**Comment by malinkinsa** [comment]
I did one more test with the latest version - 0.6.8
And the error is gone without installing `libxml2-dev libxslt-dev`.

On 0.6.7 error reproduced with `libxml2-dev libxslt-dev` and without. 

But i think we can close this issue because version 0.6.8 installing without any thoubles
